#!/bin/bash
echo ""
echo "=================================================="
echo "  F1 Data Engineering — Service Status"
echo "=================================================="
echo ""
docker exec f1_postgres pg_isready -U f1user -d f1_warehouse > /dev/null 2>&1 && echo "  🐳 PostgreSQL    → ✅ Running (port 5432)" || echo "  🐳 PostgreSQL    → ❌ Not running"
curl -s http://localhost:9000/minio/health/live > /dev/null 2>&1 && echo "  🪣 MinIO API     → ✅ Running (port 9000)" || echo "  🪣 MinIO         → ❌ Not running"
curl -s http://localhost:9000/minio/health/live > /dev/null 2>&1 && echo "  🌐 MinIO UI      → ✅ Running (port 9001)"
docker ps | grep f1_spark_master > /dev/null 2>&1 && echo "  ⚡ Spark Master  → ✅ Running (port 7077, UI: 8082)" || echo "  ⚡ Spark Master  → ❌ Not running"
docker ps | grep f1_spark_worker > /dev/null 2>&1 && echo "  ⚡ Spark Worker  → ✅ Running" || echo "  ⚡ Spark Worker  → ❌ Not running"
curl -s http://localhost:8080/health > /dev/null 2>&1 && echo "  ✈️  Airflow UI    → ✅ Running (port 8080)" || echo "  ✈️  Airflow UI    → ❌ Not running"
pgrep -f "airflow scheduler" > /dev/null 2>&1 && echo "  ⏰ Scheduler     → ✅ Running" || echo "  ⏰ Scheduler     → ❌ Not running"
echo ""
echo "  📊 Data Summary:"
[ -f "data/raw/results.csv" ] && echo "     data/raw/      → ✅ $(( $(wc -l < data/raw/results.csv) - 1 )) results rows" || echo "     data/raw/      → ❌ No data (run step01.sh)"
docker exec f1_postgres pg_isready -U f1user > /dev/null 2>&1 && COUNT=$(docker exec f1_postgres psql -U f1user -d f1_warehouse -t -c "SELECT COUNT(*) FROM fact_race_results;" 2>/dev/null | tr -d ' ') && [ "$COUNT" -gt 0 ] 2>/dev/null && echo "     PostgreSQL DWH → ✅ $COUNT race results" || echo "     PostgreSQL DWH → ❌ Empty (run step02.sh)"
BRONZE=$(python3 -c "import boto3,botocore.client as b;c=boto3.client('s3',endpoint_url='http://localhost:9000',aws_access_key_id='f1minio',aws_secret_access_key='f1minio123',config=b.Config(signature_version='s3v4'),region_name='us-east-1');print(len(c.list_objects_v2(Bucket='f1-bronze').get('Contents',[])))" 2>/dev/null || echo 0)
[ "$BRONZE" -gt 0 ] 2>/dev/null && echo "     MinIO Bronze   → ✅ $BRONZE objects in f1-bronze" || echo "     MinIO Bronze   → ❌ Empty (run step04.sh)"
SILVER=$(python3 -c "import boto3,botocore.client as b;c=boto3.client('s3',endpoint_url='http://localhost:9000',aws_access_key_id='f1minio',aws_secret_access_key='f1minio123',config=b.Config(signature_version='s3v4'),region_name='us-east-1');print(len(c.list_objects_v2(Bucket='f1-silver').get('Contents',[])))" 2>/dev/null || echo 0)
[ "$SILVER" -gt 0 ] 2>/dev/null && echo "     MinIO Silver   → ✅ $SILVER objects in f1-silver" || echo "     MinIO Silver   → ❌ Empty (run step05.sh)"
[ -d "dbt/f1_gold/spark-warehouse/gold_gold.db" ] && echo "     dbt Gold       → ✅ $(ls dbt/f1_gold/spark-warehouse/gold_gold.db 2>/dev/null | wc -l) tables" || echo "     dbt Gold       → ❌ Not built (run step06.sh)"
echo ""
echo "=================================================="
echo "  📋 Quick Commands:"
echo "  → bash scripts/start.sh          Start everything"
echo "  → bash scripts/start_postgres.sh Start PostgreSQL only"
echo "  → bash scripts/start_minio.sh    Start MinIO only"
echo "  → bash scripts/start_airflow.sh  Start Airflow only"
echo "  → bash scripts/stop.sh           Stop everything
  → bash scripts/start_spark.sh    Start Spark only
  → bash scripts/stop_spark.sh     Stop Spark only"
echo "  → bash scripts/step05.sh         Run Silver layer (PySpark)"
echo "=================================================="
echo ""
